### 1.Create a null vector of size 10 but the fifth value which is 1.

In [15]:
import numpy as np
null_vector=np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. Create a vector with values ranging from 10 to 49.

In [13]:
vector=np.arange(10,49)
print("Vector ranging form 10-49---",vector)

Vector ranging form 10-49--- [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### 3. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
matrix= np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Find indices of non-zero elements from [1,2,0,0,4,0]


In [19]:
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4], dtype=int64),)


### Create a 10x10 array with random values and find the minimum and maximum values.

In [33]:
values= np.random.randint((10,10))
Amin, Amax = values.min(), values.max()
print("minimum value : ",Amin,"\nmaximum value : ",Amax)

minimum value :  3 
maximum value :  6


In [36]:
values= np.random.random((10,10))
Amin, Amax = values.min(), values.max()
print("minimum value : ",Amin,"\nmaximum value : ",Amax)

minimum value :  0.004060511314512016 
maximum value :  0.9794808049544096


### Create a random vector of size 30 and find the mean value.

In [35]:
a = np.random.randint(30)
a = Z.mean()
print (a)

0.5720413704689039
